export const MOCK_PROFILE = {
  id: "mock-creator-1",
  name: "Alex",
  avatar: null,
  displayName: "Alex Creative",
  username: "alexcreative",
  bio: "Content creator passionate about music, lifestyle and fashion. I create authentic content that resonates.",
  country: "Nigeria",
  socialAccounts: [
    { platform: "tiktok", handle: "@alexcreative", verified: true },
  ],
  niches: ["Music", "Lifestyle"],
  rank: "rank1",
  creatorScore: 2450,
  lifetimeEarnings: 45000,
  completionRate: 75,
};

export const MOCK_CAMPAIGNS = [
  {
    id: "camp-needs-1",
    creatorHandle: "alexcreative",
    slotId: "slot-1",
    title: "Summer Vibes Playlist Promotion",
    category: "Music",
    coverImageUrl: "",
    delivery: "3 days left",
    status: "needs_content" as const,
    reward: 25000,
    viewTarget: 5000,
    minViews: 2000,
    maxViews: 5000,
    costPerView: 5,
    progress: 0,
    currentViews: 0,
    targetViews: 5000,
    contentBrief:
      "Create a 30-60 second TikTok/Reel featuring our Summer Vibes playlist. Use trending audio and show yourself vibing to the music. Include a call-to-action to listen on Spotify.",
    description:
      "Get your music discovered this summer. We're promoting the Summer Vibes playlist and want creators to show themselves genuinely vibing to the tracks.",
    brandName: "VibeScout",
    brandAvatar: null,
    scriptUrl: "https://example.com/briefs/summer-vibes-brief.pdf",
    scriptFileName: "Summer_Vibes_Brief.pdf",
    keyMessageCta: "Link in bio to listen to the full playlist",
    whatToAvoid: "No explicit content, no negative reviews of other playlists",
    platforms: ["tiktok", "instagram"],
    contentStyle: "Casual, energetic, lifestyle",
    submissionId: "",
    videoUrl: "",
    postedPlatforms: [],
    comment: "",
  },
  {
    id: "camp-review-1",
    creatorHandle: "alexcreative",
    slotId: "slot-2",
    title: "Urban Streetwear Collection",
    category: "Fashion",
    coverImageUrl: "",
    delivery: "Under review",
    status: "under_review" as const,
    reward: 35000,
    viewTarget: 8000,
    minViews: 3000,
    maxViews: 8000,
    costPerView: 4.38,
    progress: 0,
    currentViews: 0,
    targetViews: 8000,
    contentBrief:
      "Showcase the new urban streetwear collection in your own style. Minimum 45-second video showing 3 different outfits.",
    description:
      "Fresh drop from the Urban Streetwear Collection. Show off the new fits in your own style and help the collection go viral.",
    brandName: "UrbanThreads",
    brandAvatar: null,
    scriptUrl: "https://example.com/briefs/urban-streetwear-brief.pdf",
    scriptFileName: "Urban_Streetwear_Brief.pdf",
    keyMessageCta: "Shop the collection at the link in bio",
    whatToAvoid: "No competitor mentions",
    platforms: ["tiktok", "instagram"],
    contentStyle: "Street style, bold, trendy",
    submissionId: "sub-1",
    videoUrl: "https://www.tiktok.com/@alexcreative/video/123456",
    caption:
      "New drop from Musta4a is banging!!! This new jam called Pass am is so good #nusound #viral",
    videoDuration: "0:45",
    submittedAgo: "23 mins ago",
    postedPlatforms: [],
    comment: "Missed the CTA — please mention the streaming link. Doesn't follow the brief",
  },
  {
    id: "camp-live-1",
    creatorHandle: "alexcreative",
    slotId: "slot-3",
    title: "Cooking With Spices Campaign",
    category: "Food",
    coverImageUrl: "",
    delivery: "Live · tracking views",
    status: "live_tracking" as const,
    reward: 40000,
    viewTarget: 10000,
    minViews: 5000,
    maxViews: 10000,
    costPerView: 4,
    progress: 45,
    currentViews: 4500,
    targetViews: 10000,
    contentBrief:
      "Cook a meal using our spice blend and share your honest reaction. Video should be 60 seconds minimum.",
    description:
      "Our signature spice blend is the star. Cook with it, taste it, and share your honest reaction with your audience.",
    brandName: "SpiceHouse",
    brandAvatar: null,
    scriptUrl: "https://example.com/briefs/cooking-with-spices-brief.pdf",
    scriptFileName: "Cooking_With_Spices_Brief.pdf",
    keyMessageCta: "Get 20% off with code ALEX20",
    whatToAvoid: "No negative health claims",
    platforms: ["tiktok"],
    contentStyle: "ASMR cooking, close-up shots, authentic reactions",
    submissionId: "sub-2",
    videoUrl: "https://www.tiktok.com/@alexcreative/video/789012",
    caption:
      "Whipped up this coconut curry with the SpiceHouse blend — honestly shocked how good it is 🔥 Use ALEX20 at checkout!",
    videoDuration: "1:02",
    submittedAgo: "2 days ago",
    postedPlatforms: [{ platform: "tiktok", views: 4500 }],
  },
  {
    id: "camp-delivered-1",
    creatorHandle: "alexcreative",
    slotId: "slot-4",
    title: "Morning Skincare Routine",
    category: "Beauty",
    coverImageUrl: "",
    delivery: "Completed",
    status: "delivered" as const,
    reward: 30000,
    viewTarget: 6000,
    minViews: 3000,
    maxViews: 6000,
    costPerView: 5,
    progress: 100,
    currentViews: 7200,
    targetViews: 6000,
    contentBrief:
      "Film your morning skincare routine using our products. Show the before and after.",
    description:
      "A clean, effective morning skincare routine featuring our hero products. Show the routine and the results.",
    brandName: "GlowLab",
    brandAvatar: null,
    scriptUrl: "https://example.com/briefs/morning-skincare-brief.pdf",
    scriptFileName: "Morning_Skincare_Brief.pdf",
    keyMessageCta: "Tag us in your routine for a feature",
    whatToAvoid: "No medical claims about acne treatment",
    platforms: ["instagram", "tiktok"],
    contentStyle: "Clean, aesthetic, step-by-step",
    submissionId: "sub-3",
    videoUrl: "https://www.instagram.com/reel/abcdef",
    caption:
      "My 5 minute morning routine with GlowLab — skin literally feels different. Tagging them so you know it's real 💛",
    videoDuration: "0:58",
    submittedAgo: "5 days ago",
    postedPlatforms: [
      { platform: "instagram", views: 4200 },
      { platform: "tiktok", views: 3000 },
    ],
  },
];

export const MOCK_MARKETPLACE = {
  campaigns: [
    {
      id: "mp-1",
      title: "Tech Gadget Unboxing",
      category: "Tech",
      coverImageUrl: "",
      reward: 20000,
      platforms: ["tiktok", "youtube"],
      slotsLeft: 5,
      daysLeft: 12,
      targetViews: 4000,
      costPerView: 5,
      contentBrief: "Unbox and test the latest wireless earbuds. Show sound quality and comfort. Include a close-up of the product features and your genuine first impression.",
      brandName: "TechWave",
      brandAvatar: null,
      minViews: 1000,
      description: "Be one of the first to unbox and review the newest wireless earbuds on the market. Show off the features, sound quality, and your honest first impression.",
    },
    {
      id: "mp-2",
      title: "Fitness Challenge Series",
      category: "Fitness",
      coverImageUrl: "",
      reward: 45000,
      platforms: ["tiktok", "instagram"],
      slotsLeft: 3,
      daysLeft: 20,
      targetViews: 12000,
      costPerView: 3.75,
      contentBrief: "Complete our 7-day fitness challenge and document each day.",
      brandName: "FitLife",
      brandAvatar: null,
      minViews: 2000,
      description: "Take on a 7-day fitness challenge and document your journey. From warm-ups to the final day, show your progress and inspire others to get moving.",
    },
    {
      id: "mp-3",
      title: "Luxury Hotel Stay Review",
      category: "Travel",
      coverImageUrl: "",
      reward: 55000,
      platforms: ["instagram", "tiktok", "youtube"],
      slotsLeft: 2,
      daysLeft: 30,
      targetViews: 15000,
      costPerView: 3.67,
      contentBrief: "Film a full walkthrough of the hotel experience — room, pool, dining.",
      brandName: "LuxeStay",
      brandAvatar: null,
      minViews: 3000,
      description: "Experience a luxury hotel stay and share a full walkthrough — from the room and pool to the dining experience. Sell the dream of premium travel.",
    },
    {
      id: "mp-4",
      title: "Gaming Headset Review",
      category: "Gaming",
      coverImageUrl: "",
      reward: 18000,
      platforms: ["tiktok"],
      slotsLeft: 8,
      daysLeft: 10,
      targetViews: 3000,
      costPerView: 6,
      contentBrief: "Review the gaming headset — sound quality, mic test, comfort for long sessions.",
      brandName: "GameGear",
      brandAvatar: null,
      minViews: 1000,
      description: "Put the latest gaming headset through its paces. Test the sound quality, mic clarity, and comfort during long gaming sessions.",
    },
    {
      id: "mp-5",
      title: "Sustainable Fashion Haul",
      category: "Fashion",
      coverImageUrl: "",
      reward: 32000,
      platforms: ["instagram", "tiktok"],
      slotsLeft: 4,
      daysLeft: 18,
      targetViews: 7000,
      costPerView: 4.57,
      contentBrief: "Showcase a haul of sustainable/eco-friendly fashion pieces.",
      brandName: "EcoThreads",
      brandAvatar: null,
      minViews: 1000,
      description: "Showcase a curated haul of sustainable fashion pieces. Share your thoughts on eco-friendly materials, fit, and styling tips.",
    },
  ],
  activeSlots: 3,
  maxSlots: 3,
  canClaim: false,
};

export const MOCK_WALLET = {
  balance: 12500,
  lifetimeEarnings: 45000,
  completionRate: 75,
  totalReleased: 32500,
  recentTransactions: [
    {
      id: "tx-1",
      type: "credit",
      amount: 30000,
      status: "completed",
      createdAt: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000).toISOString(),
    },
    {
      id: "tx-2",
      type: "credit",
      amount: 2500,
      status: "completed",
      createdAt: new Date(Date.now() - 14 * 24 * 60 * 60 * 1000).toISOString(),
    },
    {
      id: "tx-3",
      type: "withdrawal",
      amount: 20000,
      status: "completed",
      createdAt: new Date(Date.now() - 21 * 24 * 60 * 60 * 1000).toISOString(),
    },
  ],
};
